# HealthHider

# Whether the plugin should check the 'healthider.bypass' on players.
# When this setting is enabled and the player has the permission, their client will be sent real healths.
enable-bypass-permission: false

# Which mode the 'entities' list below should operate in.
# When set to blacklist, all living entities will have their healths hidden EXCEPT for the entities listed.
# When set to whitelist, only the listed living entities will have their healths hidden.
list-mode: blacklist

# The list of entities to show or hide the health of, depending on the mode set above.
# Note that not all entities have health!
entities:
    - iron_golem # iron golems crack when they have low health
    - wolf # wolves move their tails depending on their health
